server:
  port: 8181

spring:
  application:
    name: student
  datasource:
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/student
    password: ''
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: none
